(function () {
"use strict";
const GRID_UNIT=6,MAP_SIZE=192,HALF_SIZE=MAP_SIZE/2,LEVEL_HEIGHT=6,WALL_HEIGHT=6,TARGET_PIECES=36,MAIN_ROUTE_LENGTH=16,MAX_LEVEL=1;
const DIRECTIONS=Object.freeze({N:{x:0,z:-1,opposite:"S"},E:{x:1,z:0,opposite:"W"},S:{x:0,z:1,opposite:"N"},W:{x:-1,z:0,opposite:"E"}});
const VISUAL_KITS=Object.freeze([
{id:"purple",accent:"#8177ff",emissive:"#4d42d8",trim:"#b8b4ff",wall:"#101218",ceiling:"#07080b"},
{id:"red",accent:"#ff4f69",emissive:"#bb223c",trim:"#ffc0c9",wall:"#141014",ceiling:"#090709"},
{id:"blue",accent:"#54c8ff",emissive:"#247fbd",trim:"#c5eeff",wall:"#0d1218",ceiling:"#06090c"},
{id:"green",accent:"#63df9a",emissive:"#238454",trim:"#c6f7dc",wall:"#0d1512",ceiling:"#060a08"},
{id:"white",accent:"#dce6ff",emissive:"#7489b8",trim:"#ffffff",wall:"#111318",ceiling:"#08090c"}
]);
function connector(dir,x,z,levelOffset){return{dir,x,z,levelOffset:levelOffset||0,type:"H"}}
const PIECES=Object.freeze({
spawnHub:{id:"spawnHub",name:"Spawn Hub",category:"start",width:18,depth:18,weight:0,rotations:[0],connectors:[connector("N",0,-9),connector("E",9,0),connector("S",0,9),connector("W",-9,0)],render:"spawn"},
shortStraight:{id:"shortStraight",name:"Short Straight Hall",category:"hall",width:6,depth:6,weight:11,rotations:[0,90,180,270],connectors:[connector("N",0,-3),connector("S",0,3)],render:"hall"},
mediumStraight:{id:"mediumStraight",name:"Medium Straight Hall",category:"hall",width:6,depth:12,weight:10,rotations:[0,90,180,270],connectors:[connector("N",0,-6),connector("S",0,6)],render:"hall"},
longStraight:{id:"longStraight",name:"Long Straight Hall",category:"hall",width:6,depth:18,weight:6,rotations:[0,90,180,270],connectors:[connector("N",0,-9),connector("S",0,9)],render:"hall"},
cornerHall:{id:"cornerHall",name:"Corner Hall",category:"hall",width:6,depth:6,weight:10,rotations:[0,90,180,270],connectors:[connector("N",0,-3),connector("E",3,0)],render:"corner"},
tJunction:{id:"tJunction",name:"T Junction",category:"junction",width:12,depth:12,weight:5,rotations:[0,90,180,270],connectors:[connector("N",0,-6),connector("E",6,0),connector("W",-6,0)],render:"junction"},
fourWay:{id:"fourWay",name:"Four-Way Junction",category:"junction",width:12,depth:12,weight:3,rotations:[0,90,180,270],connectors:[connector("N",0,-6),connector("E",6,0),connector("S",0,6),connector("W",-6,0)],render:"junction"},
smallRoom:{id:"smallRoom",name:"Small Empty Room",category:"room",width:12,depth:12,weight:8,rotations:[0,90,180,270],connectors:[connector("N",0,-6),connector("S",0,6)],render:"room"},
pillarRoom:{id:"pillarRoom",name:"Square Pillar Room",category:"room",width:18,depth:18,weight:4,rotations:[0,90,180,270],connectors:[connector("N",0,-9),connector("E",9,0),connector("S",0,9),connector("W",-9,0)],render:"pillars"},
steppingRoom:{id:"steppingRoom",name:"Stepping Block Room",category:"platforming",width:18,depth:12,weight:5,rotations:[0,90,180,270],connectors:[connector("N",0,-6),connector("S",0,6)],render:"steps"},
rampUp:{id:"rampUp",name:"Ramp Up",category:"vertical",width:6,depth:12,weight:1,rotations:[0,90,180,270],connectors:[connector("S",0,6,0),connector("N",0,-6,1)],render:"ramp",occupiedLevelOffsets:[0,1]},
wallCap:{id:"wallCap",name:"Plain Wall Cap",category:"cap",width:6,depth:6,weight:0,rotations:[0,90,180,270],connectors:[connector("S",0,3)],render:"cap"},
offsetSHall:{id:"offsetSHall",name:"Offset S Hall",category:"hall",width:12,depth:18,weight:7,rotations:[0,90,180,270],connectors:[connector("N",-3,-9),connector("S",3,9)],render:"offsetS"},
zigzagHall:{id:"zigzagHall",name:"Zigzag Hall",category:"hall",width:18,depth:18,weight:5,rotations:[0,90,180,270],connectors:[connector("N",-6,-9),connector("S",6,9)],render:"zigzag"},
pillarHall:{id:"pillarHall",name:"Pillar Hall",category:"hall",width:12,depth:18,weight:7,rotations:[0,90,180,270],connectors:[connector("N",0,-9),connector("S",0,9)],render:"pillarHall"},
windowedHall:{id:"windowedHall",name:"Windowed Hall",category:"hall",width:12,depth:18,weight:6,rotations:[0,90,180,270],connectors:[connector("N",0,-9),connector("S",0,9)],render:"windowed"},
lowBeamHall:{id:"lowBeamHall",name:"Low Beam Hall",category:"hall",width:12,depth:12,weight:6,rotations:[0,90,180,270],connectors:[connector("N",0,-6),connector("S",0,6)],render:"lowBeams"},
splitLevelHall:{id:"splitLevelHall",name:"Split-Level Hall",category:"platforming",width:12,depth:18,weight:5,rotations:[0,90,180,270],connectors:[connector("N",0,-9),connector("S",0,9)],render:"splitLevel"},
wideTJunction:{id:"wideTJunction",name:"Wide T Junction",category:"junction",width:18,depth:18,weight:4,rotations:[0,90,180,270],connectors:[connector("N",0,-9),connector("E",9,0),connector("W",-9,0)],render:"wideT"},
offsetCrossroads:{id:"offsetCrossroads",name:"Offset Crossroads",category:"junction",width:18,depth:18,weight:3,rotations:[0,90,180,270],connectors:[connector("N",-4,-9),connector("E",9,-4),connector("S",4,9),connector("W",-9,4)],render:"offsetCross"},
forkJunction:{id:"forkJunction",name:"Fork Junction",category:"junction",width:18,depth:18,weight:4,rotations:[0,90,180,270],connectors:[connector("S",0,9),connector("N",-5,-9),connector("E",9,-5)],render:"fork"},
doubleHallLoop:{id:"doubleHallLoop",name:"Double Hall Loop",category:"junction",width:18,depth:12,weight:3,rotations:[0,90,180,270],connectors:[connector("W",-9,-3),connector("W",-9,3),connector("E",9,-3),connector("E",9,3)],render:"doubleLoop"},
ringJunction:{id:"ringJunction",name:"Ring Junction",category:"junction",width:18,depth:18,weight:3,rotations:[0,90,180,270],connectors:[connector("N",0,-9),connector("E",9,0),connector("S",0,9),connector("W",-9,0)],render:"ring"},
brokenCrossroads:{id:"brokenCrossroads",name:"Broken Crossroads",category:"platforming",width:18,depth:18,weight:4,rotations:[0,90,180,270],connectors:[connector("N",0,-9),connector("E",9,0),connector("S",0,9),connector("W",-9,0)],render:"brokenCross"}
});
const FIRST_BATCH_IDS=Object.freeze(["spawnHub","shortStraight","mediumStraight","longStraight","cornerHall","tJunction","fourWay","smallRoom","pillarRoom","steppingRoom","rampUp","wallCap"]);
const SECOND_BATCH_IDS=Object.freeze(["offsetSHall","zigzagHall","pillarHall","windowedHall","lowBeamHall","splitLevelHall","wideTJunction","offsetCrossroads","forkJunction","doubleHallLoop","ringJunction","brokenCrossroads"]);
const EXPANSION_IDS=Object.freeze(["shortStraight","mediumStraight","longStraight","cornerHall","tJunction","fourWay","smallRoom","pillarRoom","steppingRoom",...SECOND_BATCH_IDS]);
const EXPANSION_POOL=Object.freeze(EXPANSION_IDS.map(id=>PIECES[id]));
const SECOND_BATCH=Object.freeze(SECOND_BATCH_IDS.map(id=>PIECES[id]));
function hashSeed(value){const text=String(value||"preview");let hash=2166136261>>>0;for(let i=0;i<text.length;i+=1){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619)}return hash>>>0}
function createRandom(seed){let state=hashSeed(seed)||0x6d2b79f5;return function(){state+=0x6d2b79f5;let value=state;value=Math.imul(value^(value>>>15),value|1);value^=value+Math.imul(value^(value>>>7),value|61);return((value^(value>>>14))>>>0)/4294967296}}
function rotatePoint(x,z,rotation){const n=((rotation%360)+360)%360;if(n===90)return{x:-z,z:x};if(n===180)return{x:-x,z:-z};if(n===270)return{x:z,z:-x};return{x,z}}
function rotateDirection(direction,rotation){const order=["N","E","S","W"],turns=(((((rotation%360)+360)%360)/90)|0);return order[(order.indexOf(direction)+turns)%4]}
function rotatedDimensions(definition,rotation){const n=((rotation%360)+360)%360;return n===90||n===270?{width:definition.depth,depth:definition.width}:{width:definition.width,depth:definition.depth}}
function weightedOrder(values,random){return values.map(value=>{const weight=Math.max(.1,Number(value.weight)||1);return{value,score:-Math.log(Math.max(.000001,random()))/weight}}).sort((a,b)=>a.score-b.score).map(entry=>entry.value)}
function shuffled(values,random){const copy=values.slice();for(let i=copy.length-1;i>0;i-=1){const swap=Math.floor(random()*(i+1));[copy[i],copy[swap]]=[copy[swap],copy[i]]}return copy}
function createPlacedPiece(definition,x,z,baseLevel,rotation,sequence){const dimensions=rotatedDimensions(definition,rotation),placed={id:`${definition.id}-${sequence}`,definition,x,z,baseLevel,rotation,width:dimensions.width,depth:dimensions.depth,connectors:[]};placed.connectors=definition.connectors.map((source,index)=>{const point=rotatePoint(source.x,source.z,rotation);return{id:`${placed.id}-connector-${index}`,piece:placed,source,x:x+point.x,z:z+point.z,dir:rotateDirection(source.dir,rotation),level:baseLevel+source.levelOffset,status:"open",connectedTo:null}});return placed}
function occupiedLevels(piece){return(piece.definition.occupiedLevelOffsets||[0]).map(offset=>piece.baseLevel+offset)}
function rectanglesOverlap(a,b){const epsilon=.08;return Math.abs(a.x-b.x)*2<a.width+b.width-epsilon&&Math.abs(a.z-b.z)*2<a.depth+b.depth-epsilon}
function canPlace(piece,placedPieces){if(piece.baseLevel<0||piece.baseLevel>MAX_LEVEL)return false;if(piece.x-piece.width/2<-HALF_SIZE+3||piece.x+piece.width/2>HALF_SIZE-3)return false;if(piece.z-piece.depth/2<-HALF_SIZE+3||piece.z+piece.depth/2>HALF_SIZE-3)return false;const levels=occupiedLevels(piece);for(const existing of placedPieces){const sharesLevel=occupiedLevels(existing).some(level=>levels.includes(level));if(sharesLevel&&rectanglesOverlap(piece,existing))return false}return true}
function opposite(direction){return DIRECTIONS[direction].opposite}
function tryPlaceDefinition(target,definition,layout,random){for(const rotation of shuffled(definition.rotations,random)){for(const connectorIndex of shuffled(definition.connectors.map((_,index)=>index),random)){const source=definition.connectors[connectorIndex];if(rotateDirection(source.dir,rotation)!==opposite(target.dir))continue;const baseLevel=target.level-source.levelOffset;if(definition===PIECES.rampUp&&baseLevel!==0)continue;const point=rotatePoint(source.x,source.z,rotation),candidate=createPlacedPiece(definition,target.x-point.x,target.z-point.z,baseLevel,rotation,layout.sequence++);if(!canPlace(candidate,layout.pieces))continue;const matching=candidate.connectors[connectorIndex];target.status=matching.status="connected";target.connectedTo=matching;matching.connectedTo=target;layout.pieces.push(candidate);return{piece:candidate,entry:matching}}}return null}
function placeFromPool(target,pool,layout,random){for(const definition of weightedOrder(pool,random)){const result=tryPlaceDefinition(target,definition,layout,random);if(result)return result}return null}
function openConnectors(layout){const output=[];for(const piece of layout.pieces)for(const item of piece.connectors)if(item.status==="open")output.push(item);return output}
function chooseContinuation(piece,entry,random){const options=piece.connectors.filter(item=>item!==entry&&item.status==="open");if(!options.length)return null;const forward=options.filter(item=>item.dir!==opposite(entry.dir)),pool=forward.length?forward:options;return pool[Math.floor(random()*pool.length)]}
function pairTouchingConnectors(layout){const connectors=openConnectors(layout);for(let i=0;i<connectors.length;i+=1){const first=connectors[i];if(first.status!=="open")continue;for(let j=i+1;j<connectors.length;j+=1){const second=connectors[j];if(second.status!=="open"||first.piece===second.piece)continue;if(first.level!==second.level||first.dir!==opposite(second.dir))continue;if(Math.abs(first.x-second.x)>.05||Math.abs(first.z-second.z)>.05)continue;first.status=second.status="connected";first.connectedTo=second;second.connectedTo=first;break}}}
function capConnectors(layout,random){for(const target of shuffled(openConnectors(layout),random)){if(target.status!=="open")continue;if(!tryPlaceDefinition(target,PIECES.wallCap,layout,random))target.status="sealed"}}
function placeFeatureBatch(layout,random){for(const definition of shuffled(SECOND_BATCH,random)){let placed=false;for(const target of shuffled(openConnectors(layout),random)){if(tryPlaceDefinition(target,definition,layout,random)){placed=true;break}}if(!placed)layout.missedFeatures.push(definition.id)}}
function buildLayout(seed){const random=createRandom(seed),layout={seed:String(seed||"preview"),random,sequence:1,pieces:[],kit:VISUAL_KITS[Math.floor(random()*VISUAL_KITS.length)],monsterSpawns:[],navigationPoints:[],missedFeatures:[]};const spawn=createPlacedPiece(PIECES.spawnHub,0,0,0,0,layout.sequence++);layout.pieces.push(spawn);let current=spawn.connectors[0],usedRamp=false;for(let step=0;step<MAIN_ROUTE_LENGTH&&current;step+=1){let result=null;if(step===0)result=tryPlaceDefinition(current,PIECES.mediumStraight,layout,random);else if(!usedRamp&&current.level===0){result=tryPlaceDefinition(current,PIECES.rampUp,layout,random);usedRamp=!!result}if(!result)result=placeFromPool(current,EXPANSION_POOL,layout,random);if(!result){current.status="sealed";break}current=chooseContinuation(result.piece,result.entry,random)}placeFeatureBatch(layout,random);let guard=0;while(layout.pieces.length<TARGET_PIECES&&guard<240){guard+=1;const frontier=openConnectors(layout);if(!frontier.length)break;const target=frontier[Math.floor(random()*frontier.length)];if(!placeFromPool(target,EXPANSION_POOL,layout,random))target.status="sealed"}pairTouchingConnectors(layout);capConnectors(layout,random);for(const piece of layout.pieces){if(piece.definition.category==="cap"||piece.definition.category==="start")continue;const baseY=piece.baseLevel*LEVEL_HEIGHT;layout.navigationPoints.push([piece.x,baseY,piece.z]);if(["room","junction","platforming"].includes(piece.definition.category))layout.monsterSpawns.push([piece.x,baseY,piece.z])}return layout}
window.WEIRD_VR_COMPLEX_DATA=Object.freeze({GRID_UNIT,MAP_SIZE,HALF_SIZE,LEVEL_HEIGHT,WALL_HEIGHT,DIRECTIONS,VISUAL_KITS,PIECES,FIRST_BATCH_IDS,SECOND_BATCH_IDS,rotatePoint,rotateDirection,buildLayout});
}());
